### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by ZondLV** [muertet/erepublik#6]
NULL

Fatal error: Uncaught exception 'Exception' with message 'could not generate authToken' in C:\xampp\htdocs\erepublik\classes\ApiCaller.php:90 Stack trace: #0 C:\xampp\htdocs\erepublik\classes\ApiCaller.php(19): ApiCaller->getAuthToken() #1 C:\xampp\htdocs\erepublik\classes\ApiCaller.php(36): ApiCaller->__construct(false) #2 C:\xampp\htdocs\erepublik\login.php(13): ApiCaller::get('usertoken/creat...', Array) #3 {main} thrown in C:\xampp\htdocs\erepublik\classes\ApiCaller.php on line 90

**Comment by designface** [comment]
I have the same problem. How can I solve it?
